filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            within:
                brackets: true
build:
    environment:
        php:
            version: 5.6.9
            
tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
